//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sunrise.MultipleChoice.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Sunrise.MultipleChoice.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connection Success!.
        /// </summary>
        public static string Connection_succeed {
            get {
                return ResourceManager.GetString("Connection_succeed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language Selected English.
        /// </summary>
        public static string Language_Selection {
            get {
                return ResourceManager.GetString("Language_Selection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Account.
        /// </summary>
        public static string Login_button_new_Account {
            get {
                return ResourceManager.GetString("Login_button_new_Account", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forget_Password.
        /// </summary>
        public static string Login_Forget_Password {
            get {
                return ResourceManager.GetString("Login_Forget_Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        public static string Login_Login_Button {
            get {
                return ResourceManager.GetString("Login_Login_Button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string Login_Password {
            get {
                return ResourceManager.GetString("Login_Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        public static string MessageBoxNo {
            get {
                return ResourceManager.GetString("MessageBoxNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ok.
        /// </summary>
        public static string MessageBoxOk {
            get {
                return ResourceManager.GetString("MessageBoxOk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        public static string MessageBoxYes {
            get {
                return ResourceManager.GetString("MessageBoxYes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to City.
        /// </summary>
        public static string Registation_form_city {
            get {
                return ResourceManager.GetString("Registation_form_city", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Country.
        /// </summary>
        public static string Registation_form_country {
            get {
                return ResourceManager.GetString("Registation_form_country", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string Registation_form_email {
            get {
                return ResourceManager.GetString("Registation_form_email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last name.
        /// </summary>
        public static string Registation_form_last_name {
            get {
                return ResourceManager.GetString("Registation_form_last_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string Registation_form_name {
            get {
                return ResourceManager.GetString("Registation_form_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string Registation_form_password {
            get {
                return ResourceManager.GetString("Registation_form_password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Street.
        /// </summary>
        public static string Registation_form_street {
            get {
                return ResourceManager.GetString("Registation_form_street", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Empty fields in registration form..
        /// </summary>
        public static string Registration_form_errormessages_empty_values {
            get {
                return ResourceManager.GetString("Registration_form_errormessages_empty_values", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Passwords must be identical..
        /// </summary>
        public static string Registration_form_errormessages_identical_passwords {
            get {
                return ResourceManager.GetString("Registration_form_errormessages_identical_passwords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Must select a unique email..
        /// </summary>
        public static string Registration_form_errormessages_unique_email {
            get {
                return ResourceManager.GetString("Registration_form_errormessages_unique_email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Must select a unique username..
        /// </summary>
        public static string Registration_form_errormessages_unique_username {
            get {
                return ResourceManager.GetString("Registration_form_errormessages_unique_username", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Non validate email..
        /// </summary>
        public static string Registration_form_errormessages_validate_email {
            get {
                return ResourceManager.GetString("Registration_form_errormessages_validate_email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PASSWORD Must contain at least one:.
        /// </summary>
        public static string Registration_form_errormessages_validate_password1 {
            get {
                return ResourceManager.GetString("Registration_form_errormessages_validate_password1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to lower case letter, one upper case letter.
        /// </summary>
        public static string Registration_form_errormessages_validate_password2 {
            get {
                return ResourceManager.GetString("Registration_form_errormessages_validate_password2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to one digit and one special character.
        /// </summary>
        public static string Registration_form_errormessages_validate_password3 {
            get {
                return ResourceManager.GetString("Registration_form_errormessages_validate_password3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Valid special characters are –   @#$%^&amp;+=.
        /// </summary>
        public static string Registration_form_errormessages_validate_password4 {
            get {
                return ResourceManager.GetString("Registration_form_errormessages_validate_password4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Re-enter Password.
        /// </summary>
        public static string Registration_form_Re_enter_Password {
            get {
                return ResourceManager.GetString("Registration_form_Re_enter_Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registration.
        /// </summary>
        public static string Registration_form_submit_button {
            get {
                return ResourceManager.GetString("Registration_form_submit_button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        public static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User name.
        /// </summary>
        public static string User_name {
            get {
                return ResourceManager.GetString("User_name", resourceCulture);
            }
        }
    }
}
